name: Run Python Script

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  # Optional: run on schedule (uncomment and modify as needed)
  # schedule:
  #   - cron: '0 9 * * *'  # Daily at 9 AM UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run start.py
      run: python start.py
      
    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add time.txt
        git diff --staged --quiet || git commit -m "Update time.txt with current time"
        git push